#version: '3.7'

services:
  mariadb:
    image: mariadb
    container_name: mariadb-container
    build: ./requirements/mariadb
    networks:
      - inception
    hostname: mariadb
    restart: always
    env_file:
      - .env
#    volumes:
#      - db_volume:/var/lib/mysql

  wordpress:
    image: wordpress
    container_name: wordpress-container
    build: ./requirements/wordpress
    networks:
      - inception
    hostname: wordpress
    restart: always
    env_file: 
      - .env
    depends_on:
      - mariadb
#    volumes:
#      - wordpress_volume:/

  nginx:
    image: nginx
    container_name: nginx-container
    build: ./requirements/nginx
    networks:
      - inception
    hostname: nginx
    restart: always
    env_file: 
      - .env
    depends_on:
      - wordpress
    #ports:
   #   - " 443:443"
#    volumes:
#      - wordpress_volume:/

networks:
  inception:
    driver: bridge

