#version: '3.7'

services:
  mariadb:
    container_name: mariadb-container
    build: ./requirements/mariadb
    networks:
      - inception
    hostname: mariadb
    restart: always
    env_file:
      - .env
    volumes:
       - mariadb_vol:/var/lib/mysql


  wordpress:
    container_name: wordpress-container
    build: ./requirements/wordpress
    networks:
      - inception
    hostname: wordpress
    restart: always
    env_file: 
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/html

  nginx:
    container_name: nginx-container
    build: ./requirements/nginx
    networks:
      - inception
    hostname: nginx
    restart: always
    env_file: 
      - .env
    depends_on:
      - wordpress
    ports:
      - "12443:12443"
    volumes:
      - wordpress_vol:/var/www/html

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gkrusta/data/mariadb
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gkrusta/data/wordpress